name: C++ CI

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  BasicTest:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: install cppunit
        run: sudo apt install -y libcppunit-dev
      - name: install boost
        run: sudo apt install -y libboost-all-dev
      - name: configure
        run: ./configure
      - name: make
        run: make
      - name: Basic test
        run: make basic_test
