name: C++ CI

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  QSM6Test:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: install cppunit
        run: sudo apt install -y libcppunit-dev
      - name: install boost
        run: sudo apt install -y libboost-all-dev
      - name: configure
        run: ./configure
      - name: make
        run: make
      - name: QSM6 test
        run: make QSM6_test
